=== piyushgoell/Tibco-BusinessWorks/BusinessWorks/LIB/LOGGER/LIB_UTIL_LOGGER-implement.module/Schemas/Resource/UTIL/LOGGER/ConfigFile-v1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/xsd/resource/util/logger/configfile/v1"
	xmlns:config="http://www.example.org/xsd/resource/util/logger/configfile/v1"
	elementFormDefault="qualified">

	<element name="ConfigFile" type="config:ConfigFileType" />
	<complexType name="ConfigFileType">
		<sequence>
			<element name="Logger" type="config:LoggerType" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="LoggerType">
		<sequence>
			<element name="Name" type="config:LogNameType" />
			<element name="Level" type="config:LogLevelType" />
		</sequence>
	</complexType>


	<simpleType name="LogNameType">
		<restriction base="string">
			<enumeration value="AUDIT" />
			<enumeration value="TRACE" />
			<enumeration value="LOG" />
		</restriction>
	</simpleType>


	<simpleType name="LogLevelType">
		<restriction base="string">
			<enumeration value="OFF" />
			<enumeration value="ON" />
			<enumeration value="PAYLOAD" />
		</restriction>
	</simpleType>

</schema>

=== piyushgoell/Tibco-BusinessWorks/BusinessWorks/LOGGER/LIB_UTIL_LOGGER-implement.module/Resources/UTIL/LOGGER/DefaultConfigFile/ConfigFile-v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<config:ConfigFile xmlns:config="http://www.example.org/xsd/resource/util/logger/configfile/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/xsd/resource/util/logger/configfile/v1 ConfigFile-v1.xsd ">
  <config:Logger>
    <config:Name>AUDIT</config:Name>
    <config:Level>ON</config:Level>
  </config:Logger>
  <config:Logger>
    <config:Name>TRACE</config:Name>
    <config:Level>ON</config:Level>
  </config:Logger>
  <config:Logger>
    <config:Name>LOG</config:Name>
    <config:Level>OFF</config:Level>
  </config:Logger>
</config:ConfigFile>
